SCR_MissionHeaderCombatOps {
 World "{9792BFFB7AE8CEFE}worlds/SPT_WARFARE_EDEN.ent"
 m_sName "SPT Warfare Eden"
 m_sAuthor "Spirit"
 m_sDescription "<Insert scenario description>"
 m_sDetails "<Insert scenario details>"
 m_sGameMode "Warfare"
 m_iPlayerCount 32
 m_bOverrideScenarioTimeAndWeather 1
 m_bRandomStartingDaytime 1
 m_aTaskTypesAvailable {
  SCR_ScenarioFrameworkTaskType "{5E38A8A41B55DA84}" {
   m_eTypeOfTask DELIVER
  }
  SCR_ScenarioFrameworkTaskType "{5E38A8A41B2725C3}" {
   m_eTypeOfTask DESTROY
  }
  SCR_ScenarioFrameworkTaskType "{5E38A8A41BE3799A}" {
   m_eTypeOfTask CLEAR_AREA
  }
  SCR_ScenarioFrameworkTaskType "{5E38A8A41B944989}" {
   m_eTypeOfTask KILL
  }
  SCR_ScenarioFrameworkTaskType "{5E38A8A40B5073D5}" {
   m_eTypeOfTask DEFEND
  }
 }
}